version: '3.9'

services:
  api:
    build: .
    ports:
      - 5000:5000
    environment:
      MONGO_URI: mongodb://mongo_db:27017/testdb
    volumes:
      - .:/app
    depends_on:
      - mongo_db
  mongo_db:
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db

volumes:
  mongo_db: {}