version: '3.9'

services:
  mongo_db:
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db
  api:
    build: .
    ports:
      - 3000:5000
    environment:
      MONGO_URI: mongodb://mongo_db:27017/testdb
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}